config/routes.rb
WarriorOnRails::Application.routes.draw do
  resources :warriors

  match 'play/:warrior_id' => 'play#show'

  

end

app/models/warrior.rb
class Warrior < ActiveRecord::Base
  attr_accessible :code, :level, :name, :data
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/play_controller.rb
require 'ruby_warrior'
require 'json'

class PlayController < ApplicationController

  # def index
  #   defaultWarrior = Warrior.first
  #   redirect_to :show, {warrior_id: defaultWarrior.id}
  #   # render :show, id: defaultWarrior.id
  # end

  # for json response
  def continue

    @warrior = Warrior.find( params[:id] )
    @warrior.update_attributes( params[:warrior] )

    params[:warrior_id] = params[:id]
    # render :show, id: params[:id]
    self.show

  end

  def show

    @warrior = Warrior.find( params[:warrior_id] )

    @ios = StringIO.new

    # @runner = RubyWarrior::Runner.new(ARGV, STDIN, @ios)
      @game = RubyWarrior::Game.new

    # @runner.run
      # RubyWarrior::Config.in_stream = STDIN
      RubyWarrior::Config.out_stream = @ios
      RubyWarrior::Config.delay = 0

    # @game.start
      RubyWarrior::UI.puts "Welcome to Ruby Warrior!\n"
      # @profile = RubyWarrior::Profile.load( ... )
      if @warrior.data
        @game.profile = RubyWarrior::Profile.decode( @warrior.data )
        @game.profile.level_number = @warrior.level
      else
        @game.profile = RubyWarrior::Profile.new
        @game.profile.warrior_name = @warrior.name
      end

      self.play

      @warrior.data = @game.profile.encode
      @warrior.level = @game.profile.level_number
      @warrior.save

    @message = @ios.string
    
    responseJSON = {}
    responseJSON[:frame_data] = @gameFrames.to_json

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: responseJSON }
    end

  end
  
  def play

    # @game.play_normal_mode
      # if @game.current_level.number.zero?
      # ^ skipping the if for now, as we are always starting at 0
        # prepare_next_level
          # @next_level.generate_player_files
            # @game.next_level.generate_player_files
              @game.next_level.load_level
              playerGenerator = RubyWarrior::PlayerGenerator.new(@game.next_level)
              # @readme = playerGenerator.read_template(playerGenerator.templates_path + '/README.erb')
              level = playerGenerator.previous_level
              if level.number == 0
                level = playerGenerator.level
              end
              @readme = ERB.new(File.read(playerGenerator.templates_path+'/README.erb'), nil, '-').result(binding)
              # playerGenerator.generate
                
                # if level.number == 1
                #   FileUtils.mkdir_p(level.player_path) unless File.exists? level.player_path
                #   # FileUtils.cp(playerGenerator.templates_path + '/player.rb', level.player_path) unless File.exists? (level.player_path + '/player.rb')
                # end
                
                File.open(level.player_path + '/README', 'w') do |f|
                  f.write playerGenerator.read_template(playerGenerator.templates_path + '/README.erb')
                end

                File.open(level.player_path + '/player.rb', 'w') do |f|
                  f << @warrior.code
                end

              @game.profile.level_number += 1 if @game.profile.level_number == 0

          # profile.save # this saves score and new abilities too
            # dont want to save the results from the first run until we have 'play_current_level' built out
            # @warrior.update_attributes(data:@game.profile.encode)
        RubyWarrior::UI.puts "First level has been generated.\n"
      # else
        # play_current_level
          current_level = @game.current_level
          continue = true
          current_level.load_player
          # ^ this is where we use the updated code

          RubyWarrior::UI.puts "Starting Level #{current_level.number}"

          @gameFrames ||= []
          @gameFrames += current_level.play

          if current_level.passed?
            if @game.next_level.exists?
              RubyWarrior::UI.puts "Success! You have found the stairs."
              
              RubyWarrior::Config.skip_input = false
              profile = @game.profile
              @game.profile.level_number += 1
              @game = RubyWarrior::Game.new
              @game.profile = profile
              self.play

            else
              RubyWarrior::UI.puts "CONGRATULATIONS! You have climbed to the top of the tower and rescued the fair maiden Ruby."
              continue = false
            end
            current_level.tally_points

            if @game.profile.epic?
              RubyWarrior::UI.puts final_report if final_report && !continue
            else
              @game.request_next_level
            end
          else
            continue = false
            RubyWarrior::UI.puts "Sorry, you failed level #{current_level.number}. Change your script and try again."
            if current_level.clue # && RubyWarrior::UI.ask("Would you like to read the additional clues for this level?") !RubyWarrior::Config.skip_input? &&
              RubyWarrior::UI.puts current_level.clue.hard_wrap
            end
          end

  end


end

app/controllers/warriors_controller.rb
class WarriorsController < ApplicationController
  # GET /warriors
  # GET /warriors.json
  def index
    @warriors = Warrior.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @warriors }
    end
  end

  # GET /warriors/1
  # GET /warriors/1.json
  def show
    @warrior = Warrior.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @warrior }
    end
  end

  # GET /warriors/new
  # GET /warriors/new.json
  def new
    @warrior = Warrior.new
    @warrior.code = "class Player\ndef play_turn(warrior)\n\nend\nend"

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @warrior }
    end
  end

  # GET /warriors/1/edit
  def edit
    @warrior = Warrior.find(params[:id])
  end

  # POST /warriors
  # POST /warriors.json
  def create
    @warrior = Warrior.new(params[:warrior])

    respond_to do |format|
      if @warrior.save
        format.html { redirect_to @warrior, notice: 'Warrior was successfully created.' }
        format.json { render json: @warrior, status: :created, location: @warrior }
      else
        format.html { render action: "new" }
        format.json { render json: @warrior.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /warriors/1
  # PUT /warriors/1.json
  def update
    @warrior = Warrior.find(params[:id])

    respond_to do |format|
      if @warrior.update_attributes(params[:warrior])
        format.html { redirect_to @warrior, notice: 'Warrior was successfully updated.' }
        format.json { render :text => renderActionInOtherController(PlayController,:continue,params) }
      else
        format.html { render action: "edit" }
        format.json { render json: @warrior.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /warriors/1
  # DELETE /warriors/1.json
  def destroy
    @warrior = Warrior.find(params[:id])
    @warrior.destroy

    respond_to do |format|
      format.html { redirect_to warriors_url }
      format.json { head :no_content }
    end
  end

  # obviously this is a bad idea
  def renderActionInOtherController(controller,action,params)
    # controller.class_eval{
    #   def params=(params); @params = params end
    #   def params; @params end
    # }
    c = controller.new
    c.request = @_request
    c.response = @_response
    c.params = params
    c.send(action)
    c.response.body
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/play_helper.rb
module PlayHelper
end

app/helpers/warriors_helper.rb
module WarriorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WarriorOnRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/play/show.html.erb
<script>

  window.frameData = <%= raw @gameFrames.to_json %>;

</script>
<%= javascript_include_tag "play/show" %>

<div class="content">

  <div class="panel panel_left">

    <div class="content_panel" id="title">
      <h1>InvokeStone</h1>
    </div>

    
    
    <div class="content_panel" id="craftingContainer">
      <div class="content_panel" id="craftingField">

        <div class="macro item conditional">
          <div class="conditionContainer">
            <div class="item placeholder"></div>
          </div>
          <div class="path path-true">
            <div class="item placeholder"></div>
          </div>
          <div class="path path-false">
            <div class="item placeholder"></div>
          </div>
        </div>

      </div>
    </div>

    <div class="content_panel" style="width:100%;">
      <%= form_for(@warrior, remote: true, :format => :json) do |f| %>
        <div class="actions">
          <%= f.submit %>
        </div>
        <div class="field" style="display: none;">
          <%= f.label :code %><br />
          <%= f.text_area :code %>
        </div>
      <% end %>
    </div>

    <div class="bank content_panel">
      <ul>

        <div>
          <div class="bankItem">
            <div class="item action action-move"><div class="icon run"></div></div>
          </div>
          <!-- move forward one tile -->
        </div>

        <div>
          <div class="bankItem">
            <div class="item action action-turn"><div class="icon turn"></div></div>
          </div>
          <!-- turn right -->
        </div>

        <div>
          <div class="bankItem">
            <div class="item action action-attack"><div class="icon attack"></div></div>
          </div>
          <!-- attack forward -->
        </div>

        <div>
          <div class="bankItem">
            <div class="item action action-heal"><div class="icon heal"></div></div>
          </div>
          <!-- rest 3 turns, healing 2 each -->
        </div>

        <div>
          <div class="bankItem">
            <div class="item action action-retreat"><div class="icon retreat"></div></div>
          </div>
          <!-- retreat -->
        </div>

        <div>
          <div class="bankItem">
            <div class="macro item conditional">
              <div class="conditionContainer">
                <div class="item placeholder"></div>
              </div>
              <div class="path path-true">
                <div class="item placeholder"></div>
              </div>
              <div class="path path-false">
                <div class="item placeholder"></div>
              </div>
            </div>
          </div>
          <!-- if statement structure -->
        </div>

        <div>
          <div class="bankItem">
            <div class="macro item stack">
              <div class="path">
                <div class="item placeholder"></div>
              </div>
              <div class="path">
                <div class="item placeholder"></div>
              </div>
            </div>
          </div>
          <!-- action stack -->
        </div>

        <div>
          <div class="bankItem">
            <div class="item condition condition-empty"><div class="icon blackberry"></div></div>
          </div>
            <!-- if forward tile is empty -->
          </span>
        </div>

        <div>
          <div class="bankItem">
          <div class="item condition condition-enemy"><div class="icon radish"></div></div>
          </div>
            <!-- if forward tile is enemy -->
          </span>
        </div>

        <div>
          <div class="bankItem">
          <div class="item condition condition-wall"><div class="icon acorn"></div></div>
          </div>
            <!-- if forward tile is wall -->
          </span>
        </div>

        <div>
          <div class="bankItem">
          <div class="item condition condition-lowHealth"><div class="icon cherry"></div></div>
          </div>
            <!-- if low health -->
          </span>
        </div>

      </ul>
    </div>

    <div class="content_panel" style="width:100%; height: 60px"></div>

  </div>

  <div class="panel panel_right">

    <div class="content_panel" id="map">loading...</div>
    <div class="content_panel text" id="actionsMessage">loading...</div>
    <div class="content_panel"></div>
    <div class="content_panel text" id="readMe"><%= simple_format @readme %></div>
    <div class="content_panel"></div>
    <div class="content_panel text" id="codeView">
      <pre></pre>
    </div>
    <div class="content_panel" style="height: 60px"></div>

  </div>

</div>


  

app/views/warriors/_form.html.erb
<%= form_for(@warrior) do |f| %>
  <% if @warrior.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@warrior.errors.count, "error") %> prohibited this warrior from being saved:</h2>

      <ul>
      <% @warrior.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_area :code %>
  </div>
  <div class="field">
    <%= f.label :level %><br />
    <%= f.number_field :level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/warriors/edit.html.erb
<h1>Editing warrior</h1>

<%= render 'form' %>

<%= link_to 'Show', @warrior %> |
<%= link_to 'Back', warriors_path %>

app/views/warriors/index.html.erb
<h1>Listing warriors</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Code</th>
    <th>Level</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @warriors.each do |warrior| %>
  <tr>
    <td><%= warrior.name %></td>
    <td><%= warrior.code %></td>
    <td><%= warrior.level %></td>
    <td><%= link_to 'Show', warrior %></td>
    <td><%= link_to 'Edit', edit_warrior_path(warrior) %></td>
    <td><%= link_to 'Destroy', warrior, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Warrior', new_warrior_path %>

app/views/warriors/new.html.erb
<h1>New warrior</h1>

<%= render 'form' %>

<%= link_to 'Back', warriors_path %>

app/views/warriors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @warrior.name %>
</p>

<p>
  <b>Code:</b>
  <%= @warrior.code %>
</p>

<p>
  <b>Level:</b>
  <%= @warrior.level %>
</p>


<%= link_to 'Edit', edit_warrior_path(@warrior) %> |
<%= link_to 'Back', warriors_path %>